export const emergencyFields = [
  {
    name: "name",
    label: "Nombre completo",
    placeholder: "Como aparece en tu identificacion",
    required: true,
    type: "text",
    fullWidth: true,
    maxLength: 100,
  },
  {
    name: "birthDate",
    label: "Fecha de nacimiento",
    placeholder: "",
    required: false,
    type: "date",
    fullWidth: false,
    maxLength: 100,
  },
  {
    name: "bloodType",
    label: "Tipo de sangre",
    placeholder: "",
    required: false,
    type: "select",
    fullWidth: false,
    maxLength: 100,
  },
  {
    name: "contact",
    label: "Contacto de emergencia 1",
    placeholder: "Nombre de la persona a contactar",
    required: true,
    type: "text",
    fullWidth: false,
    maxLength: 100,
  },
  {
    name: "phone",
    label: "Telefono de emergencia 1",
    placeholder: "Incluye codigo de pais, ej. 525551234567",
    required: true,
    type: "tel",
    fullWidth: false,
    maxLength: 40,
  },
  {
    name: "contact2",
    label: "Contacto de emergencia 2",
    placeholder: "Nombre de otro contacto",
    required: false,
    type: "text",
    fullWidth: false,
    maxLength: 100,
  },
  {
    name: "phone2",
    label: "Telefono de emergencia 2",
    placeholder: "Incluye codigo de pais, ej. 525551234567",
    required: false,
    type: "tel",
    fullWidth: false,
    maxLength: 40,
  },
  {
    name: "allergies",
    label: "Alergias",
    placeholder: "Medicamentos, alimentos u otras alergias",
    required: false,
    type: "textarea",
    fullWidth: true,
    maxLength: 200,
  },
  {
    name: "conditions",
    label: "Condiciones medicas",
    placeholder: "Informacion relevante en una emergencia",
    required: false,
    type: "textarea",
    fullWidth: true,
    maxLength: 200,
  },
  {
    name: "medications",
    label: "Medicamentos",
    placeholder: "Nombre y dosis, si aplica",
    required: false,
    type: "textarea",
    fullWidth: true,
    maxLength: 200,
  },
  {
    name: "notes",
    label: "Notas",
    placeholder: "Otros datos utiles en una emergencia",
    required: false,
    type: "textarea",
    fullWidth: true,
    maxLength: 200,
  },
];
export const defaultValues = Object.fromEntries(
  emergencyFields.map(({ name }) => [name, ""]),
);
export const bloodTypes = [
  "A+",
  "A-",
  "B+",
  "B-",
  "AB+",
  "AB-",
  "O+",
  "O-",
  "No lo se",
];
