import { PHONE_DIGITS } from '@/features/emergency/domain/constants/phone'
import { stripDiacritics } from '@/shared/stripDiacritics'
import texts from '@/locales/es.json'
export const emergencyFields = [
  {
    name: 'name',
    label: texts.fields.name.label,
    placeholder: texts.fields.name.placeholder,
    required: true,
    type: 'text',
    fullWidth: true,
    maxLength: 100,
  },
  {
    name: 'birthDate',
    label: texts.fields.birthDate.label,
    placeholder: texts.fields.birthDate.placeholder,
    required: false,
    type: 'date',
    fullWidth: false,
    maxLength: 100,
  },
  {
    name: 'bloodType',
    label: texts.fields.bloodType.label,
    placeholder: texts.fields.bloodType.placeholder,
    required: false,
    type: 'select',
    fullWidth: false,
    maxLength: 100,
  },
  {
    name: 'contact',
    label: texts.fields.contact.label,
    placeholder: texts.fields.contact.placeholder,
    required: true,
    type: 'text',
    fullWidth: false,
    maxLength: 100,
  },
  {
    name: 'phone',
    label: texts.fields.phone.label,
    placeholder: texts.fields.phone.placeholder,
    required: true,
    type: 'tel',
    fullWidth: false,
    maxLength: PHONE_DIGITS,
  },
  {
    name: 'contact2',
    label: texts.fields.contact2.label,
    placeholder: texts.fields.contact2.placeholder,
    required: false,
    type: 'text',
    fullWidth: false,
    maxLength: 100,
  },
  {
    name: 'phone2',
    label: texts.fields.phone2.label,
    placeholder: texts.fields.phone2.placeholder,
    required: false,
    type: 'tel',
    fullWidth: false,
    maxLength: PHONE_DIGITS,
  },
  {
    name: 'allergies',
    expandable: true,
    label: texts.fields.allergies.label,
    placeholder: texts.fields.allergies.placeholder,
    required: false,
    type: 'textarea',
    fullWidth: true,
    maxLength: 200,
  },
  {
    name: 'conditions',
    expandable: true,
    label: texts.fields.conditions.label,
    placeholder: texts.fields.conditions.placeholder,
    required: false,
    type: 'textarea',
    fullWidth: true,
    maxLength: 200,
  },
  {
    name: 'medications',
    expandable: true,
    label: texts.fields.medications.label,
    placeholder: texts.fields.medications.placeholder,
    required: false,
    type: 'textarea',
    fullWidth: true,
    maxLength: 200,
  },
  {
    name: 'notes',
    expandable: true,
    label: texts.fields.notes.label,
    placeholder: texts.fields.notes.placeholder,
    required: false,
    type: 'textarea',
    fullWidth: true,
    maxLength: 200,
  },
]
export const defaultValues = Object.fromEntries(
  emergencyFields.map(({ name }) => [name, '']),
)
export const bloodTypes = texts.common.bloodTypes.map(stripDiacritics)
